# Generated by Django 5.1.3 on 2024-12-04 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve estar no formato XXX.XXX.XXX-XX.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}\\$')])),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato XX XXXXX-XXXX', regex='^\\d{2}\\ \\d{5}\\-\\d{4}\\$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve estar no formato XXX.XXX.XXX-XX.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}\\$')])),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato XX XXXXX-XXXX', regex='^\\d{2}\\ \\d{5}\\-\\d{4}\\$')])),
                ('data_admissao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
